name = "John"
age = 45
color = input(f"Hello {name}! What color do you like?")
dict1 = {"name": name, "age": age, "color": color}
name = "Jane"
age = 42
color = input(f"Hello {name}! What color do you like?")
dict2 = {"name": name, "age": age, "color": color}
name = "Ben"
age = 30
color = input(f"Hello {name}! What color do you like?")
dict3 = {"name": name, "age": age, "color": color}
name = "Betty"
age = 19
color = input(f"Hello {name}! What color do you like?")
dict4 = {"name": name, "age": age, "color": color}
name = "Chris"
age = 24
color = input(f"Hello {name}! What color do you like?")
dict5 = {"name": name, "age": age, "color": color}
